from proxyhelper import ProxyMode, ProxyType

GLOBAL_PROXY_MODE = ProxyMode.PROXY_DIRECT
# GLOBAL_PROXY_MODE = ProxyMode.PROXY_ROTATION
# GLOBAL_PROXY_MODE = ProxyMode.PROXY_LIST
# GLOBAL_PROXY_TYPE = ProxyType.SOCKS
GLOBAL_PROXY_TYPE = ProxyType.HTTP
GLOBAL_PROXY_GET_DELAY = 60 # Delay to get new proxy